---
:verbose: false
:concurrency: 90
:logfile: ./log/sidekiq.json.log
:timeout: 4
:queues:
  - delivery_transactional
  - [delivery_immediate_high, 10]
  - [delivery_immediate, 5]
  - [process_and_generate_emails, 4]
  - [default, 3]
  - [delivery_digest, 2]
  - [email_generation_digest, 1]
  - cleanup
:schedule:
  daily_digest_initiator:
    cron: '30 8 * * * Europe/London' # every day at 8:30am
    class: DailyDigestInitiatorWorker
  weekly_digest_initiator:
    cron: '30 8 * * 6 Europe/London' # every Saturday at 8:30am
    class: WeeklyDigestInitiatorWorker
  nullify_deactivated_subscribers:
    every: '1h'
    class: NullifyDeactivatedSubscribersWorker
  email_archiver:
    every: '1h'
    class: EmailArchiveWorker
  email_deleter:
    every: '1h'
    class: EmailDeletionWorker
  digest_run_completion_marker:
    every: '1m'
    class: DigestRunCompletionMarkerWorker
  status_updates:
    every: '1m'
    class: StatusUpdateWorker
  subscription_contents:
    every: '1m'
    class: SubscriptionContentsWorker
  content_changes:
    every: '1m'
    class: ContentChangesWorker
  digest_runs:
    every: '1m'
    class: DigestRunWorker
  messages:
    every: '1m'
    class: MessagesWorker
