---
:verbose: false
:concurrency: 32
:logfile: ./log/sidekiq.json.log
:timeout: 4
# Any changes to the queues should be reflected in `docs/queues.md`.
# See https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues
# Use powers of 2: higher priority groups are checked twice as often.
:queues:
  - [delivery_transactional, 8]
  - [delivery_immediate_high, 8]
  - [process_and_generate_emails, 4]
  - [email_generation_digest, 4]
  - [delivery_immediate, 2]
  - [delivery_digest, 2]
  - [default, 1]
  - [cleanup, 1]
:schedule:
  daily_digest_initiator:
    cron: '30 8 * * * Europe/London' # every day at 8:30am
    class: DailyDigestInitiatorWorker
  weekly_digest_initiator:
    cron: '30 8 * * 6 Europe/London' # every Saturday at 8:30am
    class: WeeklyDigestInitiatorWorker
  nullify_deactivated_subscribers:
    every: '1h'
    class: NullifyDeactivatedSubscribersWorker
  email_archiver:
    every: '1h'
    class: EmailArchiveWorker
  email_deleter:
    every: '1h'
    class: EmailDeletionWorker
  digest_run_completion_marker:
    every: '1m'
    class: DigestRunCompletionMarkerWorker
  metrics_collection:
    every: '1m'
    class: MetricsCollectionWorker
